services:
  db1:
    image: postgres:15
    container_name: db1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db1
    ports:
      - "54321:5432"

  db2:
    image: postgres:15
    container_name: db2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db2
    ports:
      - "54322:5432"

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    depends_on:
      - db1
      - db2
    ports:
      - "6432:6432"
    volumes:
      - ./pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./userlist.txt:/etc/pgbouncer/userlist.txt
    command: >
      sh -c "pgbouncer -u postgres /etc/pgbouncer/pgbouncer.ini"
